INDUSTRY_KEYWORDS = {
    "电子产品": [
        {"en": "electronics supplier", "zh": "电子产品供应商"},
        {"en": "electronic components manufacturer", "zh": "电子元件制造商"},
        {"en": "consumer electronics wholesale", "zh": "消费电子批发"},
        {"en": "electronic parts distributor", "zh": "电子零件分销商"},
        {"en": "electronics factory", "zh": "电子工厂"},
    ],
    "手机配件": [
        {"en": "phone accessories supplier", "zh": "手机配件供应商"},
        {"en": "mobile phone case manufacturer", "zh": "手机壳制造商"},
        {"en": "phone charger wholesale", "zh": "手机充电器批发"},
        {"en": "screen protector factory", "zh": "屏幕保护膜工厂"},
        {"en": "mobile accessories distributor", "zh": "手机配件分销商"},
    ],
    "电脑及配件": [
        {"en": "computer hardware supplier", "zh": "电脑硬件供应商"},
        {"en": "laptop accessories manufacturer", "zh": "笔记本配件制造商"},
        {"en": "computer parts wholesale", "zh": "电脑配件批发"},
        {"en": "IT hardware distributor", "zh": "IT硬件分销商"},
        {"en": "computer peripheral factory", "zh": "电脑外设工厂"},
    ],
    "LED照明": [
        {"en": "LED lighting supplier", "zh": "LED照明供应商"},
        {"en": "LED light manufacturer", "zh": "LED灯制造商"},
        {"en": "LED lamp wholesale", "zh": "LED灯批发"},
        {"en": "LED strip factory", "zh": "LED灯带工厂"},
        {"en": "lighting fixture distributor", "zh": "灯具分销商"},
    ],
    "太阳能": [
        {"en": "solar panel supplier", "zh": "太阳能板供应商"},
        {"en": "solar energy equipment manufacturer", "zh": "太阳能设备制造商"},
        {"en": "solar inverter wholesale", "zh": "太阳能逆变器批发"},
        {"en": "solar battery factory", "zh": "太阳能电池工厂"},
        {"en": "renewable energy distributor", "zh": "可再生能源分销商"},
    ],
    "家电": [
        {"en": "home appliance supplier", "zh": "家电供应商"},
        {"en": "household appliance manufacturer", "zh": "家用电器制造商"},
        {"en": "kitchen appliance wholesale", "zh": "厨房电器批发"},
        {"en": "small appliance factory", "zh": "小家电工厂"},
        {"en": "electrical appliance distributor", "zh": "电器分销商"},
    ],
    "家具": [
        {"en": "furniture supplier", "zh": "家具供应商"},
        {"en": "furniture manufacturer", "zh": "家具制造商"},
        {"en": "office furniture wholesale", "zh": "办公家具批发"},
        {"en": "home furniture exporter", "zh": "家用家具出口商"},
        {"en": "custom furniture factory", "zh": "定制家具工厂"},
    ],
    "灯具": [
        {"en": "lighting fixture supplier", "zh": "灯具供应商"},
        {"en": "chandelier manufacturer", "zh": "吊灯制造商"},
        {"en": "decorative lighting wholesale", "zh": "装饰灯批发"},
        {"en": "ceiling light factory", "zh": "吸顶灯工厂"},
        {"en": "lamp distributor", "zh": "灯具分销商"},
    ],
    "卫浴": [
        {"en": "bathroom fixture supplier", "zh": "卫浴配件供应商"},
        {"en": "sanitary ware manufacturer", "zh": "卫浴制造商"},
        {"en": "bathroom vanity wholesale", "zh": "浴室柜批发"},
        {"en": "shower enclosure factory", "zh": "淋浴房工厂"},
        {"en": "bathroom accessory distributor", "zh": "卫浴配件分销商"},
    ],
    "建材": [
        {"en": "building material supplier", "zh": "建材供应商"},
        {"en": "construction material manufacturer", "zh": "建筑材料制造商"},
        {"en": "building supply wholesale", "zh": "建材批发"},
        {"en": "hardware material factory", "zh": "五金材料工厂"},
        {"en": "construction material distributor", "zh": "建材分销商"},
    ],
    "五金工具": [
        {"en": "hardware tools supplier", "zh": "五金工具供应商"},
        {"en": "hand tool manufacturer", "zh": "手动工具制造商"},
        {"en": "power tool wholesale", "zh": "电动工具批发"},
        {"en": "hardware factory", "zh": "五金工厂"},
        {"en": "tool distributor", "zh": "工具分销商"},
    ],
    "门窗": [
        {"en": "door window supplier", "zh": "门窗供应商"},
        {"en": "door window manufacturer", "zh": "门窗制造商"},
        {"en": "aluminum window wholesale", "zh": "铝窗批发"},
        {"en": "steel door factory", "zh": "钢门工厂"},
        {"en": "window door distributor", "zh": "门窗分销商"},
    ],
    "石材陶瓷": [
        {"en": "stone tile supplier", "zh": "石材瓷砖供应商"},
        {"en": "ceramic tile manufacturer", "zh": "瓷砖制造商"},
        {"en": "marble wholesale", "zh": "大理石批发"},
        {"en": "granite factory", "zh": "花岗岩工厂"},
        {"en": "porcelain tile distributor", "zh": "瓷砖分销商"},
    ],
    "服装": [
        {"en": "clothing supplier", "zh": "服装供应商"},
        {"en": "garment manufacturer", "zh": "服装制造商"},
        {"en": "apparel wholesale", "zh": "服装批发"},
        {"en": "textile factory", "zh": "纺织工厂"},
        {"en": "fashion clothing distributor", "zh": "时尚服装分销商"},
    ],
    "鞋类": [
        {"en": "footwear supplier", "zh": "鞋类供应商"},
        {"en": "shoe manufacturer", "zh": "鞋制造商"},
        {"en": "sneaker wholesale", "zh": "运动鞋批发"},
        {"en": "shoe factory", "zh": "鞋厂"},
        {"en": "footwear distributor", "zh": "鞋类分销商"},
    ],
    "箱包": [
        {"en": "bag supplier", "zh": "箱包供应商"},
        {"en": "luggage manufacturer", "zh": "行李箱制造商"},
        {"en": "handbag wholesale", "zh": "手提包批发"},
        {"en": "backpack factory", "zh": "背包工厂"},
        {"en": "bag distributor", "zh": "箱包分销商"},
    ],
    "纺织面料": [
        {"en": "fabric supplier", "zh": "面料供应商"},
        {"en": "textile manufacturer", "zh": "纺织品制造商"},
        {"en": "fabric wholesale", "zh": "面料批发"},
        {"en": "textile mill", "zh": "纺织厂"},
        {"en": "textile distributor", "zh": "纺织品分销商"},
    ],
    "珠宝首饰": [
        {"en": "jewelry supplier", "zh": "珠宝供应商"},
        {"en": "jewelry manufacturer", "zh": "珠宝制造商"},
        {"en": "fashion jewelry wholesale", "zh": "时尚珠宝批发"},
        {"en": "silver jewelry factory", "zh": "银饰工厂"},
        {"en": "jewelry distributor", "zh": "珠宝分销商"},
    ],
    "化妆品": [
        {"en": "cosmetics supplier", "zh": "化妆品供应商"},
        {"en": "cosmetics manufacturer", "zh": "化妆品制造商"},
        {"en": "skincare wholesale", "zh": "护肤品批发"},
        {"en": "makeup factory", "zh": "彩妆工厂"},
        {"en": "beauty product distributor", "zh": "美容产品分销商"},
    ],
    "食品饮料": [
        {"en": "food beverage supplier", "zh": "食品饮料供应商"},
        {"en": "food product manufacturer", "zh": "食品制造商"},
        {"en": "beverage wholesale", "zh": "饮料批发"},
        {"en": "snack food factory", "zh": "零食工厂"},
        {"en": "food distributor", "zh": "食品分销商"},
    ],
    "农产品": [
        {"en": "agricultural product supplier", "zh": "农产品供应商"},
        {"en": "farm produce exporter", "zh": "农产品出口商"},
        {"en": "grain wholesale", "zh": "粮食批发"},
        {"en": "fresh produce distributor", "zh": "生鲜分销商"},
        {"en": "agricultural commodity trader", "zh": "农产品贸易商"},
    ],
    "海鲜水产": [
        {"en": "seafood supplier", "zh": "海鲜供应商"},
        {"en": "fishery product exporter", "zh": "水产品出口商"},
        {"en": "frozen seafood wholesale", "zh": "冷冻海鲜批发"},
        {"en": "aquaculture farm", "zh": "水产养殖场"},
        {"en": "seafood distributor", "zh": "海鲜分销商"},
    ],
    "汽车零部件": [
        {"en": "auto parts supplier", "zh": "汽车零部件供应商"},
        {"en": "automotive parts manufacturer", "zh": "汽车零部件制造商"},
        {"en": "car accessories wholesale", "zh": "汽车配件批发"},
        {"en": "auto spare parts factory", "zh": "汽车零配件工厂"},
        {"en": "automotive parts distributor", "zh": "汽车零部件分销商"},
    ],
    "摩托车": [
        {"en": "motorcycle supplier", "zh": "摩托车供应商"},
        {"en": "motorcycle parts manufacturer", "zh": "摩托车配件制造商"},
        {"en": "motorcycle accessory wholesale", "zh": "摩托车配件批发"},
        {"en": "e-bike factory", "zh": "电动自行车工厂"},
        {"en": "motorcycle distributor", "zh": "摩托车分销商"},
    ],
    "机械设备": [
        {"en": "machinery equipment supplier", "zh": "机械设备供应商"},
        {"en": "industrial machinery manufacturer", "zh": "工业机械制造商"},
        {"en": "machine tool wholesale", "zh": "机床批发"},
        {"en": "equipment factory", "zh": "设备工厂"},
        {"en": "industrial equipment distributor", "zh": "工业设备分销商"},
    ],
    "工程机械": [
        {"en": "construction machinery supplier", "zh": "工程机械供应商"},
        {"en": "heavy equipment manufacturer", "zh": "重型设备制造商"},
        {"en": "excavator wholesale", "zh": "挖掘机批发"},
        {"en": "construction equipment dealer", "zh": "工程设备经销商"},
        {"en": "earthmoving machinery distributor", "zh": "土方机械分销商"},
    ],
    "机床": [
        {"en": "CNC machine supplier", "zh": "数控机床供应商"},
        {"en": "machine tool manufacturer", "zh": "机床制造商"},
        {"en": "lathe machine wholesale", "zh": "车床批发"},
        {"en": "milling machine factory", "zh": "铣床工厂"},
        {"en": "precision machinery distributor", "zh": "精密机械分销商"},
    ],
    "包装印刷": [
        {"en": "packaging supplier", "zh": "包装供应商"},
        {"en": "packaging material manufacturer", "zh": "包装材料制造商"},
        {"en": "printing service wholesale", "zh": "印刷服务批发"},
        {"en": "paper packaging factory", "zh": "纸包装工厂"},
        {"en": "packaging distributor", "zh": "包装分销商"},
    ],
    "塑料制品": [
        {"en": "plastic product supplier", "zh": "塑料制品供应商"},
        {"en": "plastic injection molding manufacturer", "zh": "注塑制造商"},
        {"en": "plastic material wholesale", "zh": "塑料材料批发"},
        {"en": "plastic container factory", "zh": "塑料容器工厂"},
        {"en": "plastic goods distributor", "zh": "塑料制品分销商"},
    ],
    "橡胶制品": [
        {"en": "rubber product supplier", "zh": "橡胶制品供应商"},
        {"en": "rubber seal manufacturer", "zh": "橡胶密封件制造商"},
        {"en": "rubber hose wholesale", "zh": "橡胶软管批发"},
        {"en": "rubber gasket factory", "zh": "橡胶垫片工厂"},
        {"en": "rubber parts distributor", "zh": "橡胶零件分销商"},
    ],
    "化工": [
        {"en": "chemical supplier", "zh": "化工供应商"},
        {"en": "chemical manufacturer", "zh": "化工制造商"},
        {"en": "industrial chemical wholesale", "zh": "工业化学品批发"},
        {"en": "chemical raw material factory", "zh": "化工原料工厂"},
        {"en": "chemical distributor", "zh": "化工分销商"},
    ],
    "医疗器械": [
        {"en": "medical device supplier", "zh": "医疗器械供应商"},
        {"en": "medical equipment manufacturer", "zh": "医疗设备制造商"},
        {"en": "medical supply wholesale", "zh": "医疗用品批发"},
        {"en": "surgical instrument factory", "zh": "手术器械工厂"},
        {"en": "medical product distributor", "zh": "医疗产品分销商"},
    ],
    "制药": [
        {"en": "pharmaceutical supplier", "zh": "制药供应商"},
        {"en": "pharmaceutical manufacturer", "zh": "制药制造商"},
        {"en": "medicine wholesale", "zh": "药品批发"},
        {"en": "pharma factory", "zh": "制药工厂"},
        {"en": "drug distributor", "zh": "药品分销商"},
    ],
    "实验室设备": [
        {"en": "laboratory equipment supplier", "zh": "实验室设备供应商"},
        {"en": "lab instrument manufacturer", "zh": "实验室仪器制造商"},
        {"en": "scientific equipment wholesale", "zh": "科学设备批发"},
        {"en": "lab supply distributor", "zh": "实验室用品分销商"},
        {"en": "testing equipment factory", "zh": "检测设备工厂"},
    ],
    "体育用品": [
        {"en": "sports equipment supplier", "zh": "体育用品供应商"},
        {"en": "sporting goods manufacturer", "zh": "体育用品制造商"},
        {"en": "fitness equipment wholesale", "zh": "健身器材批发"},
        {"en": "sportswear factory", "zh": "运动服装工厂"},
        {"en": "sports goods distributor", "zh": "体育用品分销商"},
    ],
    "玩具": [
        {"en": "toy supplier", "zh": "玩具供应商"},
        {"en": "toy manufacturer", "zh": "玩具制造商"},
        {"en": "plastic toy wholesale", "zh": "塑料玩具批发"},
        {"en": "educational toy factory", "zh": "益智玩具工厂"},
        {"en": "toy distributor", "zh": "玩具分销商"},
    ],
    "母婴用品": [
        {"en": "baby product supplier", "zh": "母婴用品供应商"},
        {"en": "maternity product manufacturer", "zh": "孕产用品制造商"},
        {"en": "baby care wholesale", "zh": "婴儿护理批发"},
        {"en": "children product factory", "zh": "儿童用品工厂"},
        {"en": "baby goods distributor", "zh": "母婴用品分销商"},
    ],
    "宠物用品": [
        {"en": "pet supply supplier", "zh": "宠物用品供应商"},
        {"en": "pet product manufacturer", "zh": "宠物用品制造商"},
        {"en": "pet food wholesale", "zh": "宠物食品批发"},
        {"en": "pet accessory factory", "zh": "宠物配件工厂"},
        {"en": "pet goods distributor", "zh": "宠物用品分销商"},
    ],
    "办公用品": [
        {"en": "office supply supplier", "zh": "办公用品供应商"},
        {"en": "stationery manufacturer", "zh": "文具制造商"},
        {"en": "office furniture wholesale", "zh": "办公家具批发"},
        {"en": "office equipment dealer", "zh": "办公设备经销商"},
        {"en": "school supply distributor", "zh": "学校用品分销商"},
    ],
    "安防监控": [
        {"en": "security camera supplier", "zh": "安防摄像头供应商"},
        {"en": "CCTV manufacturer", "zh": "监控制造商"},
        {"en": "surveillance system wholesale", "zh": "监控系统批发"},
        {"en": "security equipment factory", "zh": "安防设备工厂"},
        {"en": "alarm system distributor", "zh": "报警系统分销商"},
    ],
    "物流仓储": [
        {"en": "logistics service provider", "zh": "物流服务提供商"},
        {"en": "warehouse equipment supplier", "zh": "仓储设备供应商"},
        {"en": "freight forwarding company", "zh": "货运代理公司"},
        {"en": "shipping agent", "zh": "船运代理"},
        {"en": "supply chain service provider", "zh": "供应链服务商"},
    ],
    "酒店用品": [
        {"en": "hotel supply supplier", "zh": "酒店用品供应商"},
        {"en": "hotel furniture manufacturer", "zh": "酒店家具制造商"},
        {"en": "hotel linen wholesale", "zh": "酒店布草批发"},
        {"en": "hospitality product factory", "zh": "酒店用品工厂"},
        {"en": "hotel equipment distributor", "zh": "酒店设备分销商"},
    ],
    "礼品促销品": [
        {"en": "promotional gift supplier", "zh": "促销礼品供应商"},
        {"en": "corporate gift manufacturer", "zh": "企业礼品制造商"},
        {"en": "custom gift wholesale", "zh": "定制礼品批发"},
        {"en": "souvenir factory", "zh": "纪念品工厂"},
        {"en": "advertising gift distributor", "zh": "广告礼品分销商"},
    ],
    "眼镜": [
        {"en": "eyewear supplier", "zh": "眼镜供应商"},
        {"en": "optical frame manufacturer", "zh": "眼镜框制造商"},
        {"en": "sunglasses wholesale", "zh": "太阳镜批发"},
        {"en": "reading glasses factory", "zh": "老花镜工厂"},
        {"en": "optical lens distributor", "zh": "光学镜片分销商"},
    ],
    "钟表": [
        {"en": "watch supplier", "zh": "钟表供应商"},
        {"en": "watch manufacturer", "zh": "钟表制造商"},
        {"en": "timepiece wholesale", "zh": "钟表批发"},
        {"en": "clock factory", "zh": "钟表工厂"},
        {"en": "watch distributor", "zh": "钟表分销商"},
    ],
    "乐器": [
        {"en": "musical instrument supplier", "zh": "乐器供应商"},
        {"en": "guitar manufacturer", "zh": "吉他制造商"},
        {"en": "music instrument wholesale", "zh": "乐器批发"},
        {"en": "musical equipment factory", "zh": "乐器设备工厂"},
        {"en": "instrument distributor", "zh": "乐器分销商"},
    ],
    "电动车": [
        {"en": "electric vehicle supplier", "zh": "电动车供应商"},
        {"en": "electric scooter manufacturer", "zh": "电动滑板车制造商"},
        {"en": "e-bike wholesale", "zh": "电动自行车批发"},
        {"en": "electric tricycle factory", "zh": "电动三轮车工厂"},
        {"en": "EV parts distributor", "zh": "电动车零件分销商"},
    ],
    "电缆电线": [
        {"en": "cable wire supplier", "zh": "电缆电线供应商"},
        {"en": "electrical cable manufacturer", "zh": "电缆制造商"},
        {"en": "power cable wholesale", "zh": "电力电缆批发"},
        {"en": "wire harness factory", "zh": "线束工厂"},
        {"en": "electrical wire distributor", "zh": "电线分销商"},
    ],
}
